/**
 * Land dots for the contact globe: points of a Fibonacci sphere that fall on
 * land in Natural Earth's 110m land polygons, stored as a bitset (one bit per
 * sphere point). Regenerate with the same N and point formula if it changes.
 */
const POINTS = 16_000;
const GOLDEN_ANGLE = Math.PI * (3 - Math.sqrt(5));
const LAND_BITSET =
  "AAAAAAAAABAAQkBIAAhJIQshJISEhIAUEBJCgkLAAJk6IQNgYAAMhJEDMjIADsTYgZk5Mkdi7sjMuplpcfEsbu3MprzXNv/6Stvf+zt/f+3t/u2Vv7/+9t732tv5/ztvf+ft/f+dt/v21v7+2lt5eztv9++tvN21t/L3Vsbu31t5Oysn5e+snJ2Xk3J3VmbO3Um5OSMr5+ak7JyR03JzQn7OzUmZOSMv5+aE7Jy70zNzQn7OzInZOTG3Z+bk/Jybk3NzRm7Pzen5OTU35+bk3Jyb03NzSm7Ozem5OTW35+bU3Jybk3Nzak7Pzek5OTUn5+T0nJyb03Nzam7Pzak5OTW35+bUnJybU3Nyam7Ozam5OTWn4+bUnJybUXNzakbGzak5OTGj5ubUnIybUXNyakbNzeg5OTOj5uTEjIqTkXN6akbFyYg5NSOj5+TEjIqREXNqTk7FyYkZNScmZ9SEnIqTE3NqRkzMyYk5FSMmZtSEmIiRE3NqRkzOqQk5FSMmZtSUmJyTE3JqRk7MqAk5ESOmZtSEjJ6RUzJiRkzNiAkZPSOmZvSEmJoREzJ6RkzN6AkZNSOmZNSEmJpREzJqRkzJ6Ak5NSOmZNSEmJLRUzJqTkzJqAkxJaemZNSEmJJRU3JqTkzJqSkxJaem5NSUmJJTUnJqSk3JKSkxJaem5JSUmJJTUGJKSknJKSkxJaek5NSUkpJTUGJKSknJKCklJaekxFSckpJTUGpKSknJKCglJaekxJSUkpJTUEpKSkmJKCklBaek1BSckgJTUEoKSkmpKCklBaeklBSckgJTUkoKSkmpKCklBaamlBSUkkJTUkoKSEmpoSklBaaklBSQmkJBUkoKTEmhqSA1BYaElFSQkkJBQEoqDAkpKSA1hYaklBSQkkJBQGoqDAmpKSAlhYaA1BQQkkJBQGoKCgGpKSAkhYaA1BQQglJBQEoKCwGpISAEhYKA1BQUglJCQGgKCQGpKSAUhYCA0BQWglJCQCgKCQGpKSAEpYCAUBQWAlJCQCgKCQEhICgEpYCAUBQSAlJQQAgKCQEhICQEpICAUBQSAlJAQQgKCQUhISQEpICCUFQSAkJCQQhoCQUhoCQEhISCUFASCkJCQShICQUhqCwEpISCUFASCkJAUQgICQUhoCwUpISCUFASCkJAUQgICQUhoCQUhICCEFASCkJAUSgISQUBoCQUlYCCEFASigJAQSgoQAUBoCQVFYCCAFAQCgJAQSgqQAUBoCAVFICCQFQACgJAQSgqAAWBqAAVBICCUFQACgJAQSgqAAWBqAAVBICiUFQACgJRASgoAAWBqAAVBKACUFQACgJRASoqAAWgqAAVBKICUFAACgJRESooAAWgqAAVFKICUFAACkBRASooBAWgoAgVFKIiUFQECkhRESooBAWkoAgUEIICUFQMCkhBESooBgXkoAgUEIICUFQMCkhBESogBgWkoAgUEIICUFAMCkhBESogBkWkoAgUEIICUECMCkhBESogBAWgoBgVkIIiUECICkhBESggBAWgoBAUkIICUEAMCkBBASggBAWggBAUkKICUEAICkBBASggBAWggBAUgIICUEAICkBBASggBQWggBAUgIIiUEAICkABISgCBQWggBAUgYICUAQKCkABISgKBUWgiBAUgIICUAQKCkARISgABUWgiBQUgCICUBQKCkARISgCBUWgKBQUgCIDUAQKikBRKSgCRUSgKBQUgCICUASKiEBRCCgCRQSgKBQQgaICUASKiEBRKCgCRQSgCBQRgaIQUASKiEBRKCICRUSgCBQRgaIQVASKiEARKCICRQGoCBQRgaJQVASKiFARKCICRQGoCBQRgSJQRASKglARKCICRaGoCBQBoSJQRASKglARKAICRaCICBQBoSJQBASKgBARKAJCRaAICBQBoSJQBASKgBERKAJCRaAICBQBISJQBASKQBERKAJCRaAICBQBIyJQBASKQBEQKAJCRKAICBQBIyBQBISIQBEQKAJGRKAICBQBIiBQBISIQBEQKAJGQKAICBABIiBQAISAQAEQIABEQKAACBGBIiBAAIiAQAEQIAAEQIAACAGBAiAAAAiAAAEQAAAEQIAAEAAAAiAAAAiAAAEQAAAEQIAAEAAAAiAAAAiEAAEgAAAEQgAAEAAAAgAAAAgEAAAgAAAEAAAAEAAAAEAAAAgAAAAgAAAEQAAAEAgAAEAAAACAAAAgEAAAgAAAEAAAAEAgAACAAAAgAAAAgEAAAAAAAEAAAAAAgQAgAAAAgAAAAAAAAEAAAAAAgQAAAAAAgAAAAAAAAEAAAAAAAQAAAAAAgAAAAAACAAAAAAAAAQAAAAAAgAEAAAACAAAAAAAAAQAAAAQAAAAAEAACAAAAAAAAAQAAAAQAAAAAAAAAAAAAAAAAAQAAAAQAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAACAAACSkRICQgBISUgpISUjJASUFJKSkZpKSkdJaWn9LSWjtPSWlpOS29paT0/p+f1/Jyf1/Nzfl7Pz/v5Pb/v9/f9vN6f3/N7fn/v7//9/f////8=";

export type Vec3 = [x: number, y: number, z: number];

/** Unit vector for a latitude/longitude in degrees: y points north, z faces 0° longitude. */
export function toUnitVector(latDeg: number, lonDeg: number): Vec3 {
  const lat = (latDeg * Math.PI) / 180;
  const lon = (lonDeg * Math.PI) / 180;
  return [Math.cos(lat) * Math.sin(lon), Math.sin(lat), Math.cos(lat) * Math.cos(lon)];
}

let cache: Float32Array | undefined;

/** Land dots as packed unit vectors [x0, y0, z0, x1, y1, z1, …]. */
export function landDots(): Float32Array {
  if (cache) return cache;
  const bytes = Uint8Array.from(atob(LAND_BITSET), (c) => c.charCodeAt(0));
  const out: number[] = [];
  for (let i = 0; i < POINTS; i++) {
    if (!(bytes[i >> 3]! & (1 << (i & 7)))) continue;
    const y = 1 - ((i + 0.5) * 2) / POINTS;
    const r = Math.sqrt(1 - y * y);
    const phi = i * GOLDEN_ANGLE;
    const lat = (Math.asin(y) * 180) / Math.PI;
    const lon = (Math.atan2(Math.sin(phi) * r, Math.cos(phi) * r) * 180) / Math.PI;
    out.push(...toUnitVector(lat, lon));
  }
  cache = Float32Array.from(out);
  return cache;
}
